# Generated by Django 4.2.28 on 2026-03-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups messages into a conversation thread.')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('client_id', models.IntegerField(blank=True, help_text='Optional client context for RAG namespace scoping.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['advocate', 'conversation_id', 'created_at'], name='webhooks_ch_advocat_98c656_idx')],
            },
        ),
    ]
