# Generated by Django 4.2.28 on 2026-02-27 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.TextField(help_text='Storage path for the file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed')], default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('processed_output_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['advocate', '-created_at'], name='documents_d_advocat_363191_idx'), models.Index(fields=['case'], name='documents_d_case_id_528e86_idx'), models.Index(fields=['status'], name='documents_d_status_07369e_idx')],
            },
        ),
    ]
