# Generated by Django 4.2.28 on 2026-03-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.TextField(help_text='Storage path for the file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed')], default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('processed_output_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_status_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Document status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['advocate', '-created_at'], name='documents_d_advocat_363191_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case'], name='documents_d_case_id_528e86_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
