# Generated by Django 4.2.28 on 2026-02-28 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_status_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Document status histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
