# Generated by Django 4.2.28 on 2026-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_html_path',
            field=models.TextField(blank=True, help_text='Storage path for validated HTML output', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_json_path',
            field=models.TextField(blank=True, help_text='Storage path for consolidated JSON output', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_report_path',
            field=models.TextField(blank=True, help_text='Storage path for validation report', null=True),
        ),
    ]
