# Generated by Django 4.2.28 on 2026-03-14 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_add_processed_file_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('html_path', models.TextField(blank=True, help_text="Storage path for this version's HTML")),
                ('json_path', models.TextField(blank=True, help_text="Storage path for this version's JSON")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch_id', models.CharField(help_text='Unique identifier within the HTML, e.g. "mismatch-1"', max_length=50)),
                ('field_label', models.CharField(blank=True, help_text='Human-readable label for the field, e.g. "Salutation"', max_length=255)),
                ('original_text', models.TextField(help_text='Text from the original document')),
                ('suggested_text', models.TextField(help_text='AI-suggested correction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=10)),
                ('resolved_text', models.TextField(blank=True, help_text='Final text after human decision (for edited mismatches)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score 0.0-1.0', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='documents.document')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_mismatches', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='documents.documentversion')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('document', 'mismatch_id')},
            },
        ),
    ]
