# Generated by Django 4.2.28 on 2026-03-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentversion_documentmismatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_pdf_path',
            field=models.TextField(blank=True, help_text='Storage path for generated PDF from finalized HTML', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('finalized', 'Finalized')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('finalized', 'Finalized')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatushistory',
            name='to_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('ready_to_process', 'Ready to Process'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('finalized', 'Finalized')], max_length=20),
        ),
    ]
