# Generated by Django 4.2.28 on 2026-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_finalized_status_and_extracted_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='corrections_log_path',
            field=models.TextField(blank=True, help_text='Storage path for corrections log', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='html_v2_path',
            field=models.TextField(blank=True, help_text='Storage path for finalized v2 HTML (clean, no editing UI)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='txt_v2_path',
            field=models.TextField(blank=True, help_text='Storage path for v2 TXT file (for RAG indexing)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_html_path',
            field=models.TextField(blank=True, help_text='Storage path for validated HTML output (v1 HTML with editing UI)', null=True),
        ),
    ]
