# Generated by Django 4.2.28 on 2026-03-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_add_v2_file_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('v1_html_received', 'V1 HTML Received'), ('v1_html_modified', 'V1 HTML Modified'), ('version_saved', 'Version Saved'), ('version_reverted', 'Version Reverted'), ('save_export', 'Save & Export'), ('pdf_generated', 'PDF Generated'), ('rag_push', 'Pushed to RAG'), ('rag_response', 'RAG Response'), ('chat_sent', 'Chat Message Sent'), ('chat_received', 'Chat Response Received'), ('status_change', 'Status Changed'), ('processing_started', 'Processing Started'), ('processing_complete', 'Processing Complete')], max_length=30)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='documents_d_documen_49a22e_idx')],
            },
        ),
    ]
